version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        restart: always
        ports:
        - "8000:80"
        volumes:        
        - web_data:/web
        - ./log:/var/log/nginx              
        depends_on:
        - web
        
    web:
        container_name: web
        build: ./web
        restart: always
        command: uwsgi --ini uwsgi.ini
        ports:
        - "8002:8000"
        volumes:
        - web_data:/web

volumes:
    web_data:
