version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx
        build: ./nginx
        restart: always
        ports:
          - "8080:80"
        volumes:
          - web_data:/srv/ec2-docker-compose
          - ./log:/var/log/nginx
        depends_on:
          - web

    web:
        container_name: web
        build: ./web
        restart: always
        command: uwsgi --ini uwsgi.ini
        ports:
          - "8002:8000"
        volumes:
          - web_data:/srv/ec2-docker-compose
          - ./log:/var/log/uwsgi
        depends_on:
          - db

volumes:
    web_data:
    pgdata:

