version: '3'
services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    image: himanmen/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/tmp
      - ./log:/var/log/nginx
    depends_on:
      - web

  web:
    container_name: web
    image: himanmen/web
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./web:/tmp
      - ./log:/var/log/uwsgi
    depends_on:
      - db
volumes:
  pgdata:

